exports.appName = 'restaurantr';

exports.Constants = {
    MINIMUM_RATING: 0,
    MAXIMUM_RATING: 5,
};

exports.actions = {
    FETCH_RESTAURANT: 'FETCH_RESTAURANT',
    FETCH_REVIEW: 'FETCH_REVIEW',
    FETCH_RESTAURANTS: 'FETCH_RESTAURANTS',
    FETCH_USER_DATA: 'FETCH_USER_DATA',
    FETCH_OTHER_USER_DATA: 'FETCH_OTHER_USER_DATA',
    CLEAR_USER_DATA: 'CLEAR_USER_DATA',
}
